# Generated by Django 5.0 on 2023-12-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folder',
            new_name='Group',
        ),
    ]
