# Generated by Django 5.0 on 2023-12-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_rename_folder_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='folder',
            new_name='group',
        ),
    ]
