# Generated by Django 5.0 on 2023-12-17 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_note_created_at_note_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='coeditors',
        ),
        migrations.AddField(
            model_name='note',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
