# Generated by Django 5.0 on 2023-12-25 18:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0006_note_is_private_note_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
