# Generated by Django 5.0 on 2024-01-25 07:27

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0009_alter_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
